import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import About from './about'
import Header from './header.js'
import Activity from './Activity.js'
import Skills from './Skills.js'
import Frog from './form.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>けいご-webデザイナー</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <About/>
      <Activity/>
      <Skills/>
      <Frog/>
      </div>
  )
}
